//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Exception.Resources {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionsResources {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionsResources() { }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Exception.Resources.ExceptionsResources", typeof(ExceptionsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        // Auth
        public static string UserNotFound => ResourceManager.GetString("UserNotFound", resourceCulture)!;
        public static string InvalidCredentials => ResourceManager.GetString("InvalidCredentials", resourceCulture)!;
        public static string EmailAlreadyExists => ResourceManager.GetString("EmailAlreadyExists", resourceCulture)!;
        public static string MemberRoleNotFound => ResourceManager.GetString("MemberRoleNotFound", resourceCulture)!;

        // Book
        public static string BookNotFound => ResourceManager.GetString("BookNotFound", resourceCulture)!;
        public static string BookOutOfStock => ResourceManager.GetString("BookOutOfStock", resourceCulture)!;

        // UserBook
        public static string UserBookNotFound => ResourceManager.GetString("UserBookNotFound", resourceCulture)!;
        public static string UserBookNotOwned => ResourceManager.GetString("UserBookNotOwned", resourceCulture)!;
        public static string MaxBorrowLimitReached => ResourceManager.GetString("MaxBorrowLimitReached", resourceCulture)!;
        public static string UserBanned => ResourceManager.GetString("UserBanned", resourceCulture)!;
        public static string InvalidRating => ResourceManager.GetString("InvalidRating", resourceCulture)!;

        // Fine
        public static string FineNotFound => ResourceManager.GetString("FineNotFound", resourceCulture)!;
        public static string FineAlreadyPaid => ResourceManager.GetString("FineAlreadyPaid", resourceCulture)!;
        public static string FineNotOwned => ResourceManager.GetString("FineNotOwned", resourceCulture)!;

        // Notification
        public static string NotificationNotFound => ResourceManager.GetString("NotificationNotFound", resourceCulture)!;
        public static string NotificationNotOwned => ResourceManager.GetString("NotificationNotOwned", resourceCulture)!;

        // Role
        public static string RoleNotFound => ResourceManager.GetString("RoleNotFound", resourceCulture)!;
        public static string RoleAlreadyExists => ResourceManager.GetString("RoleAlreadyExists", resourceCulture)!;
        public static string UserRoleNotFound => ResourceManager.GetString("UserRoleNotFound", resourceCulture)!;

        // User
        public static string UserAlreadyBanned => ResourceManager.GetString("UserAlreadyBanned", resourceCulture)!;
        public static string UserNotBanned => ResourceManager.GetString("UserNotBanned", resourceCulture)!;

        // Category
        public static string CategoryNotFound => ResourceManager.GetString("CategoryNotFound", resourceCulture)!;
    }
}
