//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShelfManager.Application.Handlers.Books.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        internal ValidationMessages() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShelfManager.Application.Handlers.Books.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string Name_Required => ResourceManager.GetString("Name_Required", resourceCulture)!;
        public static string Name_MaxLength => ResourceManager.GetString("Name_MaxLength", resourceCulture)!;
        public static string Description_MaxLength => ResourceManager.GetString("Description_MaxLength", resourceCulture)!;
        public static string Author_Required => ResourceManager.GetString("Author_Required", resourceCulture)!;
        public static string Author_MaxLength => ResourceManager.GetString("Author_MaxLength", resourceCulture)!;
        public static string PageCount_GreaterThanZero => ResourceManager.GetString("PageCount_GreaterThanZero", resourceCulture)!;
        public static string StockCount_GreaterThanOrEqualZero => ResourceManager.GetString("StockCount_GreaterThanOrEqualZero", resourceCulture)!;
        public static string TotalCount_GreaterThanZero => ResourceManager.GetString("TotalCount_GreaterThanZero", resourceCulture)!;
        public static string PublishYear_Required => ResourceManager.GetString("PublishYear_Required", resourceCulture)!;
        public static string Publisher_Required => ResourceManager.GetString("Publisher_Required", resourceCulture)!;
        public static string Code_Required => ResourceManager.GetString("Code_Required", resourceCulture)!;
        public static string CategoryId_Required => ResourceManager.GetString("CategoryId_Required", resourceCulture)!;
    }
}
